### ISSUE TITLE
Credentials not found in github action

### ISSUE THREAD

**Issue by gr8temi** [rrainn/dynamodb-action#12]
I have a pipeline like this
```
name: "Lint and Test"
description: "Run linters"

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v4.0.0

    - name: Set up cache for Poetry dependencies
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry/cache
          ~/.cache/pypoetry/artifacts
          .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Poetry
      run: |
        pip install poetry
      shell: bash

    - name: Install dependencies
      run: |
        poetry lock --no-update 
        poetry install --no-interaction --no-ansi
      shell: bash

    - name: Run linters
      run: |
        poetry run isort .
        poetry run black .
        poetry run pylint **/*.py
        poetry run pytest
      shell: bash
```

But when the test runs I keep getting this error
` ERROR tests/test_webhook.py::test_webhook_decode_token_failed - pynamodb.exceptions.TableError: Unable to describe table: Unable to locate credentials`

How best do I run the pipeline
