### ISSUE TITLE
Instance is running, but unavailable

### ISSUE THREAD

**Issue by ilyanesteroff** [rrainn/dynamodb-action#9]
Hi!
When using dynamodb-action for unit tests on ubuntu-latest with actions, the instance is running, netstat shows something at 8000. But running lsof -i :8000 exits with 1 indicating the instance is unavailable. 

netstat log on port 8000: 
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN  

Here is the workflow file:

```
name: Deployment
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Start DynamoDB
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 8000
          cors: "*"

      - name: netstat
        run: netstat -l

      - name: Check DynamoDB
        run: lsof -i :8000

      - name: Deps
        run: npm i

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build:ci
```

The same situation is happening when using amazon/dynamodb-local with services
Here is the config:

```
name: Deployment
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: netstat
        run: netstat -l

      - name: Check DynamoDB
        run: lsof -i :8000

      - name: Deps
        run: npm i

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build:ci
```

Stuck on this isssue, wondering whether there is a problem with Github-actions, DynamoDB or config, I would appreciate any assistance on this 😅
